# Generated by Django 4.2.1 on 2024-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('earn', models.FloatField()),
                ('clicks', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
