# Generated by Django 4.2.1 on 2024-02-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('verif_email', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='piramid/static/piramid/images')),
                ('balance', models.FloatField(default=0)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('clicks', models.IntegerField(default=0)),
                ('ref_code', models.IntegerField(default=None)),
                ('inviter', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='piramid/static/piramid/images'),
        ),
    ]
