# Generated by Django 4.2.1 on 2024-04-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0002_referral_profit_dollars'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='status',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
