# Generated by Django 4.2.1 on 2024-02-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0002_user_alter_products_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
