# Generated by Django 4.2.1 on 2024-02-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
