# Generated by Django 4.2.1 on 2024-02-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inviter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_code',
            field=models.IntegerField(default=0),
        ),
    ]
