# Generated by Django 4.2.1 on 2024-02-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0007_alter_user_inviter_alter_user_ref_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
