# Generated by Django 4.2.1 on 2024-02-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0008_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
