# Generated by Django 4.2.1 on 2024-03-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0009_user_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
