# Generated by Django 4.2.1 on 2024-03-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0010_user_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_product',
            field=models.IntegerField(default=None),
        ),
    ]
