# Generated by Django 4.2.1 on 2024-04-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0011_user_active_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit_sum',
            field=models.FloatField(default=0),
        ),
    ]
