# Generated by Django 4.2.1 on 2024-04-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0012_user_deposit_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refferals_profit',
            field=models.FloatField(default=0),
        ),
    ]
