# Generated by Django 4.2.1 on 2024-04-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0013_user_refferals_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_time',
            field=models.FloatField(default=0),
        ),
    ]
