# Generated by Django 4.2.1 on 2024-04-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piramid', '0015_invoices_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='piramid.user')),
            ],
        ),
    ]
